name: test

schemes:
    test:
        build:
            targets:
                test: all
        run:
            environmentVariables:
                VULKAN_SDK: $(PROJECT_DIR)/Libraries/vulkansdk/macOS
                VK_LAYER_PATH: $(PROJECT_DIR)/Libraries/vulkansdk/macOS/share/vulkan/explicit_layer.d
                VK_ICD_FILENAMES: $(PROJECT_DIR)/Libraries/vulkansdk/macOS/share/vulkan/icd.d/MoltenVK_icd.json
        test:
            environmentVariables:
                VULKAN_SDK: $(PROJECT_DIR)/Libraries/vulkansdk/macOS
                VK_LAYER_PATH: $(PROJECT_DIR)/Libraries/vulkansdk/macOS/share/vulkan/explicit_layer.d
                VK_ICD_FILENAMES: $(PROJECT_DIR)/Libraries/vulkansdk/macOS/share/vulkan/icd.d/MoltenVK_icd.json
        profile:
            environmentVariables:
                VULKAN_SDK: $(PROJECT_DIR)/Libraries/vulkansdk/macOS
                VK_LAYER_PATH: $(PROJECT_DIR)/Libraries/vulkansdk/macOS/share/vulkan/explicit_layer.d
                VK_ICD_FILENAMES: $(PROJECT_DIR)/Libraries/vulkansdk/macOS/share/vulkan/icd.d/MoltenVK_icd.json

options:
    createIntermediateGroups: true
    usesTabs: false
    indentWidth: 4
    tabWidth: 4

settings:
    GCC_C_LANGUAGE_STANDARD: c11

targets:
    test:
        type: application
        platform: macOS
        info:
            path: Generated/Info.plist
        entitlements:
            path: Generated/app.entitlements
        sources:
            - path: ../src
              excludes:
                - "shaders/*.frag"
                - "shaders/*.vert"
            - path: ../src/shaders
              buildPhase: sources
        settings:
            HEADER_SEARCH_PATHS:
                - $(PROJECT_DIR)/Libraries/vulkansdk/MoltenVK/include
                - $(PROJECT_DIR)/Libraries/glfw/include
                - $(PROJECT_DIR)/Libraries/cglm/include
                - $(PROJECT_DIR)/Libraries/stb_image/include
            LIBRARY_SEARCH_PATHS:
                - $(PROJECT_DIR)/Libraries/vulkansdk/macOS/lib
                - $(PROJECT_DIR)/Libraries/glfw/lib
                - $(PROJECT_DIR)/Libraries/cglm/lib
        dependencies:
            - framework: $(PROJECT_DIR)/Libraries/vulkansdk/macOS/lib/libvulkan.1.dylib
            - sdk: Metal.framework
            - sdk: IOSurface.framework
            - sdk: QuartzCore.framework
            - framework: $(PROJECT_DIR)/Libraries/glfw/lib/libglfw3.a
              embed: false
            - sdk: Cocoa.framework
            - sdk: IOKit.framework
            - framework: $(PROJECT_DIR)/Libraries/cglm/lib/libcglm.a
              embed: false
        buildRules:
            - filePattern: "*.frag *.vert"
              script: $PROJECT_DIR/Libraries/vulkansdk/macOS/bin/glslc $INPUT_FILE_DIR/$INPUT_FILE_NAME -o $BUILT_PRODUCTS_DIR/shaders/$INPUT_FILE_NAME.spv
              outputFiles:
                  - $BUILT_PRODUCTS_DIR/shaders/$INPUT_FILE_NAME.spv
        postBuildScripts:
            - script: cp $PROJECT_DIR/../res/fonts/*.fnt* $BUILT_PRODUCTS_DIR/fonts/
            - script: cp $PROJECT_DIR/../res/sdf/*.png $BUILT_PRODUCTS_DIR/sdf/
            - script: cp $PROJECT_DIR/../res/msdf/*.png $BUILT_PRODUCTS_DIR/msdf/
